### ISSUE TITLE
questions/suggestions

### ISSUE THREAD

**Issue by hentman** [Sn0wCrack/ExHentai-Archive#1]
Hi, haven't tested your program yet (lazy for setting up all the servers) but seems good
as I have understand it will change exhentai interface and allows to download galeries and easilly allows reading them on the same interface

does it save all tags for being able to search by tag later?

I'm looking for something that:
- [X] mark visited galeries (even better if only marks when reaching last page and/or allowing some way to "unmark")
- [x] highlight function can be usefull, I use it for highlighting on green english translated doujins

~~show which tags from tag perk are on that doujin, maybe not even needing tag perk?~~

here's an example of my current exhentai, as you can see, english galeries are green and readed galeries are a bit transparent this was done using eh plus:
http://snag.gy/Fjygb.jpg

Main feature I'm looking for is some way to keep updated about my favourite authors, being able to see a list of translated doujins pending to be read for each favourite author, I would be able to do this just by searching all my favourite author names, but exhentai search is limited to a few words, so no idea about how to implement that

could you add these features to your project or I'm asking too much?

**Comment by Sn0wCrack** [comment]
Hey there hentman,
Glad to be getting some suggestions  finally.
To keep updated there is the feeds feature, which unfortunatly isnt to user friendly right now, be enables the crawling of a ExHentai search query in your case something like "author:Name language: English" 

A highlighting function should be fairly easy to implement, as would visited gallaries, but I'm not sure how inclined I am to the later really, when you can simply tag it yourself a particular colour, as not all users may want this.

And yes, as you can see by the description or screenshot, the ExHentai search system is in tact and all the galleries tags are moved with it.

And as for your interpretation of the programming, it doesn't do anything to ExHentai besides adding a download button to each gallery, this program functions as an independent website host on your local machine

**Comment by hentman** [comment]
"To keep updated there is the feeds feature, which unfortunatly isnt to user friendly right now, be enables the crawling of a ExHentai search query in your case something like "author:Name language: English" "

but how can I search multiple authors at same time when there's a word limit on exhentai search?

edit: I added you on skype

**Comment by Sn0wCrack** [comment]
You can set up more than one feed at a time.

And yes, I'm not going to be adding anyone on Skype, as its a personal account, all discussion pertaining to this stays here.

**Comment by Sn0wCrack** [comment]
I've come back to updating with some of these ideas, I've currently implimented the marking read galleries partially

**Comment by Sn0wCrack** [comment]
Added all that I can.
