### ISSUE TITLE
 .

### ISSUE THREAD

**Issue by ghost** [Sn0wCrack/ExHentai-Archive#10]

**Comment by Sn0wCrack** [comment]
Well give n the error message, you don't have Virtual Box installed, didn't really think about adding it to the setup guide after all.

You can download it here: https://www.virtualbox.org/wiki/Downloads

**Comment by Samariz** [comment]
This work with VMware too ? because i have VMware, so what i do ?

**Comment by Samariz** [comment]
I downloaded this Vagrant VMwar prodivder : https://github.com/orishavit/vagrant-vmware-free

Can i use it ? where i install it ?

**Comment by Samariz** [comment]
@Sn0wCrack up

**Comment by Samariz** [comment]
I would like to not have to install virtualbox because i already have VMware

**Comment by Sn0wCrack** [comment]
If you don't know what you're doing with that plugin, as it seems old and outdated and may no longer be compatible, it also requires manual compilation, I would recommend to not even trying it, and just simply setting up VirtualBox as, the only endorsed way to use VMWare currently with Vagrant is through a payed add-on from Vagrant's creators.

**Comment by Samariz** [comment]
> If you don't know what you're doing

Lol in everything i do, i have no idea what im doing , but sometime when i spend 10 hours of my time and try everything i can do, it work

I will try with VirtulBox later, now i have another problem to fix , i tryed to update my network card driver because i have a problem and i can't change my dns, but now i can't reinstall or activate it -_-, 
If you have and idea for fix that.
![image](https://user-images.githubusercontent.com/31006418/29325420-dd7c8b4a-81e7-11e7-86b1-6ce26bc85463.png)
(im so fucking toxic to ask you to fix all my issues xd)

Well i tell you later if vagrant work with virtual box and if i can watch fucking hentai in my computer

**Comment by Samariz** [comment]
I still don't have fix my Ethernet prob, but i  have do vagrant with virtual box, i needed to activate virtualization technology in bios, and change the port 443 to 444, because 443 was "already taken by another apps" or something like that , i only changed the host port, i don't know if i need to change guest to.
![image](https://user-images.githubusercontent.com/31006418/29347170-e74a208e-824a-11e7-94a1-2e127010b9f4.png)

So i think the machine is working but, when i try to go on https://localhost/ or https://localhost/vagrant/TaskRunner.php?task=Full

its white screen on firefox and " HTTP ERROR 403 Access to localhost was denied You are not authorized to view this page." on chrome and both tell that the connection is not securised 

![image](https://user-images.githubusercontent.com/31006418/29347263-ab34885e-824b-11e7-8b1a-0d3f526e3d1e.png)

![image](https://user-images.githubusercontent.com/31006418/29347291-e8bb25e8-824b-11e7-86d8-ef4eb95e8693.png)

**Comment by Samariz** [comment]
OKAY, i saved my data in another disk and reinstaled windows, now my Ethernet problem is fix.

So what you recomend me to do the Vagrant setup with your help, OR the Windows Setup with a lot for your help ? 

(I would like to do the windows setup) I mean if you don't need virtualbox, for the windows setup, i will be sure to not have have another problem with my Ethernet Driver

**Comment by Samariz** [comment]
@Sn0wCrack 
Hey, my friend, your still there ?

**Comment by Sn0wCrack** [comment]
Since you changed the port you need to access the site via "https://localhost:444/" now

**Comment by Samariz** [comment]
:O
![image](https://user-images.githubusercontent.com/31006418/29397610-c8c40dfc-831f-11e7-8c98-eb4acb8e500f.png)

THAT AWESOME

**Comment by Samariz** [comment]
@Sn0wCrack 
HELP,

When i do add to archive, nothing happen.

and that don't add to archive.

Finaly, i use the port 443, because i reinstalled my windows, and that fixed this prob,

So i just do "https://localhost/".

I tryed to add folder path in config.json.linux 
         "tempDir": "D:\exhen\temp",
        "archiveDir": "D:\exhen\archive",
        "imagesDir": "D:\exhen\images"

but that change nothing, Hmm , 

maybe editing the config.json or config.json.win32 ?

I don't know, i wait your answer. (i don't want to destroy everything one more time xd)

**Comment by Samariz** [comment]
Maybe i need firefox ? im using chrome

**Comment by Sn0wCrack** [comment]
You don't need to change those paths, you need to actually now download those archives as this does not happen automatically as specified here: https://github.com/Sn0wCrack/ExHentai-Archive/blob/master/setup/Vagrant-Setup.md#archiving

**Comment by Sn0wCrack** [comment]
You are also able to ssh into the vagrant instance and run the "php TaskRunner.php Archive" command yourself

**Comment by Samariz** [comment]
It is this BUTTON ? 


![image](https://user-images.githubusercontent.com/31006418/29403773-9968d92e-8339-11e7-9c88-6e843690c491.png)

Because that don't work

And WOW Wow wow, just who the hell do you think i am, i have no idea of what is "php TaskRunner.php Archive" 

Here nothing : 

![image](https://user-images.githubusercontent.com/31006418/29404463-5dc772c0-833b-11e7-9b68-9c59bf0c694d.png)

And i can't drag and drop the user script, or i get error message, so i used tampermonkey

![image](https://user-images.githubusercontent.com/31006418/29405041-111b21ae-833d-11e7-996b-214456e948a2.png)

"Applications, addons and user scripts can't be add from this Web site" (It does it everywhere)

**Comment by Samariz** [comment]
@Sn0wCrack

**Comment by Samariz** [comment]
If you have a discord server or irc for fix my prob faster this could be nice

**Comment by Sn0wCrack** [comment]
Yes you need to press add to archive and _then_ run the Archive task, and you don't drag and drop the userscript as is, it must be configured with your servers values first before placing it into Tampermonkey, you also don't drag it onto the page, but onto a new tab or use File -> Open as described in the guide.

**Comment by Lalien** [comment]
I hope you all burn in hell like the little niggers you are

**Comment by Samariz** [comment]
> I hope you all burn in hell like the little niggers you are

That's racist

**Comment by Samariz** [comment]
@Sn0wCrack 

Okay , look at this : https://sendvid.com/a4az4kfp

**Comment by Sn0wCrack** [comment]
Alright, I need to see what you've edited the user  script too in Tampermonkey to actually ensure you've set that part up correctly, you can find your scripts in tampermonkey by clicking on the icon and then going to dashboard.

**Comment by Samariz** [comment]
config.json.linux  : 

> {
	"base": {
		"accessKey": "changeme",
        "autoReadPercentage": 80,
		"viewType": "mpv",
		"cookie": {
            "ipb_member_id": "28XXXX6",
            "ipb_pass_hash": "8f4bXXXX7XXXXXXXXXXXXXXXXXXXX543e",
            "hath_perks": "m1.m2.m3.tf.t1.t2.t3.p1.p2.s-210aa44613",
            "uconfig": "tl_m-uh_y-tr_2-ts_m-prn_y-dm_l-ar_1-cats_350-xns_0-xl_1024x2048x1x2049x10x1034x2058x20x1044x2068x30x1054x2078x40x1064x2088x50x1074x2098x60x1084x2108x70x1094x2118x80x1104x2128x90x1114x2138x100x1124x2148x110x1134x2158x120x1144x2168x130x1154x2178x255x1279x2303-rc_2-rx_0-ry_0-ms_n-mt_n-sa_y-oi_n-qb_n-tf_n-hp_-hk_"
        },
		"tempDir": "./temp",
        "archiveDir": "./archive",
        "imagesDir": "./images"
	},
	"default": {
		"db": {
			"dsn": "mysql:host=localhost;dbname=exhen",
			"user": "root",
			"pass": "changeme"
		},
		"sphinxql": {
			"dsn": "mysql:host=127.0.0.1;port=9306;dbname=exhen",
			"user": "root",
			"pass": ""
		},
		"memcache": {
			"host": "localhost",
			"port": 11211
		},
		"indexer": {
			"full": "sudo indexer --rotate galleries suggested"
		}
	}
}

userscript.user.js

// ==UserScript==
// @name       ExHentai Archive
// @match      *://exhentai.org/*
// @match      *://e-hentai.org/*
// @require    https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js
// ==/UserScript==

var baseUrl = 'https://localhost/';
var key = 'changeme';

function createArchiveLink(gid, token) {
    var link = $('<a href="#">Send to archive</a>');
    link.data('gid', gid);
    link.data('token', token);
    
    link.on('click', function() {
        $.getJSON(baseUrl + 'api.php', { action: 'addgallery', gid: link.data('gid'), token: link.data('token'), key: key }, function(data, result) {
            if(data.ret === true && result === 'success') {
                $(link).css({
                    color: '#777',
                    pointerEvents: 'none'
                });
            }
            else {
                alert('An error occured while adding to archive');
            }
        });
        
        return false;
    });
    
    return link;
}

$('div#gd5').each(function() { //archive button on gallery detail
    var container = $(this);
    
    $.getJSON(baseUrl + 'api.php', { action: 'hasgallery', gid: gid, key: key }, function(data, result) {
        if(data.data.exists) {
            var p = $('<p class="g2"><img src="//exhentai.org/img/mr.gif"> </p>');
            var link = "";
            if (data.data.deleted == 0) {
               link = $('<a href="#" target="_blank">Archived</a>');
            } else if (data.data.deleted >= 1) {
                link = $('<a href="#">Deleted</a>');
            }
            
            if(data.data.archived && data.data.deleted == 0) {
                link.prop('href', baseUrl + '?' + $.param({ action: 'gallery', id: data.data.id }));
            }
            else if (!data.data.archived) {
                link.on('click', function() {
                    alert('Not yet downloaded');
                    return false;
                });
            }
            
            link.appendTo(p);
            $('.g2', container).last().after(p);
        }
        else {
            var p = $('<p class="g2"><img src="//exhentai.org/img/mr.gif"> </p>');
            var link = createArchiveLink(gid, token);
            link.appendTo(p);
            
            $('.g2', container).last().after(p);
        }
    });
});

$('div.itg').each(function() { //gallery search
    var container = $(this);
    var galleries = $('div.id1', container);
    var gids = [ ];
    
    galleries.each(function() {
        var galleryContainer = $(this);
        var link = $('div.id2 a', galleryContainer).prop('href');
        
        var bits = link.split("/");
        
        var gid = bits[4];
        var token = bits[5];
        
        gids.push(gid);
        
        galleryContainer.data('gid', gid);
        $('.id44 img', galleryContainer).remove();
        
        $.getJSON(baseUrl + 'api.php', { action: 'hasgallery', gid: gid, key: key }, function(data, result) {
           if (!data.data.exists) {
              var link = createArchiveLink(gid, token);
              link.css({ fontSize: '9px' });
              link.on('click', function() {
                  $(this).parents('.id1').css({ background: 'green' });
              });
        
              link.prependTo($('.id44 div', galleryContainer));
           } else {
             var res = "";
             if (data.data.archived && data.data.deleted == 0) {
                res = $('<p>Archived</p>');
                galleryContainer.css({background: 'green'});
             }
               
             if (data.data.deleted >= 1) {
               res = $('<p>Deleted</p>');  
               galleryContainer.css({background: '#AA0000'});
             }
             res.prependTo($('.id44 div', galleryContainer));
           }
        });
    });
});

![image](https://user-images.githubusercontent.com/31006418/29482191-2b53fcde-848d-11e7-8dbf-384140592e51.png)

![image](https://user-images.githubusercontent.com/31006418/29482206-5c7febc4-848d-11e7-9ee2-5d0629d08e7e.png)

![image](https://user-images.githubusercontent.com/31006418/29482210-6a3e37d4-848d-11e7-977b-6fba219d0403.png)


that's all, i think

**Comment by Samariz** [comment]
I have the power to always have strange problem, i remember one time i tried to setup a desktop vps with debian haha, this taked me one week xD.

**Comment by Samariz** [comment]
And did you see the video ? i don't know why but the site auto delete it, but i can reupload it somewhere else if you want.

**Comment by Samariz** [comment]
@Sn0wCrack

**Comment by Samariz** [comment]
@Sn0wCrack

**Comment by Sn0wCrack** [comment]
Yes, from the video it looked like an error with your userscript, and those errors are normal.
It seems there may be an issue with connecting to the virtual machine, I'll need to take a further look into this.

**Comment by Sn0wCrack** [comment]
Okay, I've narrowed down the issue to seemingly be that sphinx search for some reason runs into an issue with opening it's own pid file, seemingly stemming from searchd starting multiple times after its installation.

**Comment by Sn0wCrack** [comment]
Okay, I appear to have resolved the issue.
You'll need to redownload the repository, and re-run the vagrant setup.
If you're running it in the same folder, delete the .vagrant before running vagrant up again.

All should work as expected hopefully.

**Comment by Samariz** [comment]
Okay its a bit better, but still have a problem xd

Video part 1 (installation, see if i did something wrong) : https://streamable.com/hy8bi
Video part 2 (problem) :  https://streamable.com/3qiq0
(the site don't let upload more then 10 min video :/)

**Comment by Samariz** [comment]
And what SPV and MPV mean

And how i delete an archive

**Comment by Samariz** [comment]
@Sn0wCrack

**Comment by Sn0wCrack** [comment]
The issue currently seems to lie in getting the download link for the galleries. I'd double check your config file is correct (mainly the cookie section), if it is incorrect, you will need to run "vagrant destroy" and then "vagrant up" after having edited it, as it is only copied over upon the creation of the vagrant box.

SPV and MPV are just the viewer modes, single page viewer and multi page viewer, meaning how many to display at the same time.

**EDIT:** Looking over your setup you seem to have done everything correctly, I cannot say for certain as to why it's failing to grab the archive links for you as I ran the exact same setup and have managed to get it to work. Only thing I might suggest is copying your own uconfig and perks cookies over the ones in the config.json.linux file.

**Comment by Samariz** [comment]
Huuu, and where if find "uconfig and perks cookies" ?

![image](https://user-images.githubusercontent.com/31006418/29606320-2ce60cea-87ee-11e7-8cf4-3d33a21ce1bf.png)

![image](https://user-images.githubusercontent.com/31006418/29606255-fbfb2aca-87ed-11e7-9934-5752c4197938.png)

**Comment by Samariz** [comment]
@Sn0wCrack

**Comment by Sn0wCrack** [comment]
Actually just as a test, after visiting that task runner page and attempting to download a gallery, could you upload a .html file to pastebin or something, you can find them under "archive/page" in the ExHentai-Archive directory, the error seems to be coming from not finding the download link in that file.

**Comment by Samariz** [comment]
@Sn0wCrack 

https://pastebin.com/VCe9NTdT

**Comment by Sn0wCrack** [comment]
Well I think I see what the issue is, just to confirm, if you change the files extension to .jpg, is it now a picture of a Sad Panda?

**Comment by Samariz** [comment]
:O https://streamable.com/n4p4n

**Comment by Samariz** [comment]
@Sn0wCrack

**Comment by Samariz** [comment]
But i'm able to access the site :/ ,  i use Simple DNS Plus : http://simpledns.com/
because DNS of my ISPblock Exhentai , so my dns is 127.0.0.1 in IPV4 and ::1 in IPV6
So maybe the problem come from here ?

**Comment by Samariz** [comment]
@Sn0wCrack

**Comment by Samariz** [comment]
I got a brilliant idea ! Maybe if i change DNS of virtualbox virtual Ethernet adapter to localhost too, this  will work ?  
![image](https://user-images.githubusercontent.com/31006418/29725037-0ca82c4a-89cb-11e7-9f84-303e2b5ea491.png)

, I try

**Comment by Samariz** [comment]
@Sn0wCrack 
aH, nevermind , im retarded, still sadpanda xd

Well if u have an idea xd

**Comment by Samariz** [comment]
And it was stupid because when ISP block exhentai this don't show sadpanda xd

**Comment by Samariz** [comment]
So what do i do ?

**Comment by Sn0wCrack** [comment]
The error wouldn't be from an ISP block, as you can see the Sadpanda, the Sadpanda is from not having a logged in cookie, it's interesting to see this happen, as you can seemingly access the site perfectly fine, but via ExHentai-Archive you cannot, I've tried myself with the same config file from the repo (using my own ipb password and username) and it appears to work perfectly fine.

It could be DNS related? As VirtualBox uses your main adapter settings (So the Ethernet one in this case). Perhaps try setting it to 8.8.8.8 and 8.8.4.4 (the Google DNS) and try again (it may require a restart to fully take effect).

TBH: this is an interesting issue.

**Comment by Samariz** [comment]
@Sn0wCrack 

> TBH: this is an interesting issue.

Man, its always like that with me, i have the power to get problem that nobody have. I remenber one time i tryed to setup a Destkop Debian Vps with putty, this take me 3 weeks xd

**Comment by Samariz** [comment]
I redownloaded the repository, and this time i tryed with E-hentai (not e"x"hentai) cookies and now i have tag and hentai name, but that all xd

And now its html code and not sadpanda : https://pastebin.com/LLDnNmMu
                                                                     https://pastebin.com/Wh5UNrmx
![image](https://user-images.githubusercontent.com/31006418/29741435-55d43966-8a6d-11e7-8282-895aa7e74628.png)
(Don't judge me on the tags, i downloaded something random xd)

But still not downloading the hentai :  https://pastebin.com/p5vnJsJf

**Comment by Sn0wCrack** [comment]
I'll note down that e-hentai cookies are what's required rather than the exhentai ones for the future, didn't think there was any difference tbh.

As for that error, it's more than likely due to the fact you don't have enough Credits or GP on exhentai to actually download the archive, the error is misleading and I've corrected this in the in the last update. 
Check the gallery's "Archive Download" link to see the cost of said download.

**Comment by Samariz** [comment]
"Credits or GP " what ? it is the currency you earn by hosting Exhentai on a server with Hentai@Home 
 : https://ehwiki.org/wiki/Hentai@Home  ??? I think i can do that , i have 300mb/s optic fiber, but i can't let my computer always on, u think a raspberry pi is fine for this ?

And looks like i have a problem of synchronisation with my E-hentai account and Exhentai i can't acces "my galleries" and "favorites" on exhentai : https://streamable.com/ve0hr
                                                                     https://streamable.com/zh9e5

I don't know what to do ;/

**Comment by Samariz** [comment]
Oh nevermind, there is already a tutorial for rapsberry pi
![image](https://user-images.githubusercontent.com/31006418/29743172-7871bf06-8a8c-11e7-8412-7f47ea1a9dc2.png)

**Comment by Samariz** [comment]
@Sn0wCrack

**Comment by Samariz** [comment]
Well i think we need to fix my sync prob i guess, maybe delete cookies ? cache ? i don't know i don't want to fuck everything xd

**Comment by Sn0wCrack** [comment]
Your current issue with this software is still seemingly about not having GP or Credits to download as far as I can tell, you'll need to do anything else yourself.

You can check  the currencies here: https://e-hentai.org/exchange.php?t=gp

**Comment by Samariz** [comment]
I fixed my prob by deleting cookies.

**Comment by Samariz** [comment]
Well, thanks you for all the help ^^.
