### ISSUE TITLE
database error

### ISSUE THREAD

**Issue by qxzg** [Sn0wCrack/ExHentai-Archive#17]
Request url:`http://exhen.localhost/api.php?search=&page=0&order=posted&action=galleries`
Error message:
```
<b>Fatal error</b>:  Uncaught exception 'PDOException' with message 'Could not connect to database (exhen).' in /home/wwwroot/exhen/lib/rb.php:422
Stack trace:
#0 /home/wwwroot/exhen/lib/rb.php(253): RedBean_Driver_PDO-&gt;connect()
#1 /home/wwwroot/exhen/lib/rb.php(431): RedBean_Driver_PDO-&gt;runQuery('select * from g...', Array)
#2 /home/wwwroot/exhen/lib/rb.php(2339): RedBean_Driver_PDO-&gt;GetAll('select * from g...', Array)
#3 /home/wwwroot/exhen/lib/rb.php(9111): RedBean_Adapter_DBAdapter-&gt;get('select * from g...', Array)
#4 /home/wwwroot/exhen/lib/rb.php(9886): RedBean_Facade::query('get', 'select * from g...', Array)
#5 /home/wwwroot/exhen/classes/SphinxQL.php(30): RedBean_Facade::getAll('select * from g...', Array)
#6 /home/wwwroot/exhen/classes/Model/Gallery.php(78): SphinxQL::query('select * from g...', Array)
#7 /home/wwwroot/exhen/classes/ApiHandler.php(28): Model_Gallery::search('0', 24, '', 'posted', 0, false, false, false)
#8 /home/wwwroot/exhen/classes/ApiHandler.php(542): ApiHandler-&gt;galleriesAction()
#9 /home/wwwroot/e in <b>/home/wwwroot/exhen/lib/rb.php</b> on line <b>422</b><br />
```
![Snipaste_3-17-16_55_22](https://user-images.githubusercontent.com/30212669/76848776-38205600-687f-11ea-9ee8-05136abec9f8.png)

Environment:

- Ubuntu 18.04.3 LTS
- php 5.6.40
- Mysql 5.6.46
- nginx 1.16.1

**Comment by Sn0wCrack** [comment]
Double check you've correctly set up your config.json file with the correct credentials.

As well as that ensure you've created that database in your MySQL instance and imported db.sql into it.

**Comment by qxzg** [comment]
I think I have set up my database and config file correctly.
Because the url like `api.php?action=hasgallery&gid=1591104&key=xxx` and the `Archive` task are working properly.
![Snipaste_3-18-8_37_25](https://user-images.githubusercontent.com/30212669/76916352-24b2d080-68fb-11ea-99fa-124fb205524f.png)

![Snipaste_3-18-9_16_48](https://user-images.githubusercontent.com/30212669/76915902-d0f3b780-68f9-11ea-8c15-109f4a7cb845.png)

**Comment by Sn0wCrack** [comment]
Oh wait, apologies, that function is actually querying your Sphinx instance, and not your MySQL instance.

Based on the output of your Sphinx instance, it's failing to create the pid file, you should ensure the directory /etc/sphinxsearch exists and that the user it's being run under has permission to read and write within it.

If you're using the sphinx.conf.linux that's provided in the repo, you'll probably just want to run the following:
```
sudo mkdir -p /etc/sphinxsearch/log
sudo mkdir -p /var/lib/sphinxsearch/data/exhen/
```

**Comment by qxzg** [comment]
Now it works, thank you
