### ISSUE TITLE
Failed to load, Error 500

### ISSUE THREAD

**Issue by ZeroDrako** [Sn0wCrack/ExHentai-Archive#2]
Hi, today i install your program. All ok in the setup, but at search for anything i get nothing.
In the console show:

> Failed to load resource: **http://127.0.0.1:8080/api.php?search=&page=0&order=posted&action=galleries** the server responded with a status of 500 (Internal Server Error)

The error is from the server but i don't get it, is from e-hentai server ? or local server?
Info:
-Used "Vagrant Setup" (currently trying "Windows Setup"...)
-Windows 8.1 (Admi)
-Virtualbox & Vagrant (last version)
-Default value at "accessKey" (if change, nothing happend)
Thanks.

**Comment by Sn0wCrack** [comment]
EDIT:
I've just re-read your post.
I think you've misinterpreted what this software does, it's not a front end for ExHentai, it's a way to organise archived downloads in an easy manner.
It doesn't cheat any systems inplace on ExHentai, such as getting your free archive downloads either.

Perhaps read over this section of the readme: https://github.com/Sn0wCrack/ExHentai-Archive#what-is-exhentai-archive

However, I'm wondering where you're getting that error message, as with the latest version of the repo I don't appear to be getting any status code 500s, perhaps you could include what browser you're using?

However, you did make me realise I didn't setup a way for Vagrant users to archive there queued downlaods.

**Comment by ZeroDrako** [comment]
I've take 3. Hope this help.

![Image 2](http://i1236.photobucket.com/albums/ff444/ZeroDrako/sshot-2_zpsrm2yasoz.png)
 i will check,thanks.

**Comment by Sn0wCrack** [comment]
Okay @ZeroDrako,

I've done quite a bit of updating, I've adding actually archiving from the Vagrant setup now.

I'd like to check one thing for your specific case however, did you install the Virtual Box Guest Extensions?
You can find it **[here.](http://download.virtualbox.org/virtualbox/5.1.2/Oracle_VM_VirtualBox_Extension_Pack-5.1.2-108956.vbox-extpack)**

As well as install the Vagrant plugin for Virtual Box Guest Extensions, by running `vagrant plugin install vagrant-vbguest`? (Try running the command with a command prompt inside where all the ExHentai-Archive files are located)

If you didn't do both of those things, run `vagrant destroy` and then after executing that `vagrant up` once more to purge the box. (Both of these commands need to be run from inside the ExHentai-Archive folder) 

I'll be commiting my new update soon, so perhaps hold off until then.

**EDIT:**
New update is out, try updating to the latest and then try the above

**Comment by ZeroDrako** [comment]
Yes, installed VirtualBox +  Guest Extensions...

Well, i re install from zero. Still have a conexion problem, but now is a problem over https.
I think the problem is HTTPS...
I've trying load exhentai in http but the problem persist. Change the "header" to allow the error is gone but nothing happened. 
![](http://i1236.photobucket.com/albums/ff444/ZeroDrako/85af2efc-f398-4d17-93aa-27a2927c31f2_zpsep4vxrqc.png)
PD: yes, i've misinterpreted, i thought i could also search on the local server to download directly from it :/

**Update:**
Nevermind, i've given up.

> Clean Install over clean windows, no antivirus, no firewall, nothing else, clean Chrome+TM... still error on connection.

The project look very good. Thanks anyway..

**Comment by Sn0wCrack** [comment]
I'm still going to keep looking into this, on my end everything works from scratch, but I'll take another look.

Perhaps it has something to do with Chromium. I'll keep investigating.

**UPDATE 1:**

I've gotten Chromium with a barebones setup and it all works flawlessly, I don't recieve any of the same errors.

Can you check the network tab for me, finding when that request is run? I'd like to see the response header for it, as mine is indeed returning Access-Control-Allow-Origin \* with the header.

I'll add CORS to the Vagrant Apache configuration file, however CORS is returned by the API handler when it sends back the JSON data.

**UPDATE 2:**

I've actually managed to get this error to occur on my end now. I believe it's somehow related to the virtual box version Vagrant seems to install automatically, 5.0.10, however previously I was using 5.0.20 with no issues, I'll try this again and see what happens.

**UPDATE 3:**

I've narrowed down the root of the problem to be Sphinx. For some reason it seems to be creating a search daemon without me ever call for the search daemon, this would be a good thing, if the search daemon could be connected to. It seems Sphinx's indexer makes this if searchd isn't called and does indeed make the indexs, but fails to close the process and locks up Sphinx, the process can also only be accessed by indexer.

Anyways, working on a fix right now.

**EDIT:**
Also with the new update, you're required to head to https://localhost/ first and add an exception for the self-signed certificate there, then proceed to the ExHentai, however as of right now that's no the issue, just a heads up.
You should also only ever be using ExHentai.org over HTTPS now.

**Comment by Sn0wCrack** [comment]
@ZeroDrako

I've fixed the issue.

You'll want to redownload the repo and run the `vagrant destroy` command in the ExHentai-Archive directory once more and then run `vagrant up` afterwards then run `vagrant halt` and then run `vagrant up` once more. The issue will be fixed from then on (or so I believe)

Sorry for all the hastle.
