### ISSUE TITLE
Galleries not showing up?

### ISSUE THREAD

**Issue by YukiSakuma** [Sn0wCrack/ExHentai-Archive#6]
I am following the vagrant setup. I've already input my ipb_member_id and ipb_pass_hash values in the config.json.linux file before

Sorry I am just new to this.
![test](https://cloud.githubusercontent.com/assets/16185735/23477200/2e7f8bf0-fef8-11e6-823c-68f87efb823d.JPG)

![hjtttp](https://cloud.githubusercontent.com/assets/16185735/23472897/561bc962-fee9-11e6-88ae-9a420f1c2e0d.JPG)
![e](https://cloud.githubusercontent.com/assets/16185735/23475711/5470633e-fef3-11e6-9bf3-9ff5823a5a3a.JPG)

I dragged the userscript to firefox my browser of choice. I am using Windows 7 x64 
My baseUrl is https://localhost

**Comment by Sn0wCrack** [comment]
Dumb question here.
But have you actually marked any galleries for archive?

**Comment by YukiSakuma** [comment]
How do I "mark" the galleries?

**Comment by Sn0wCrack** [comment]
You go to ExHentai and press on the "Send to Archive" button that appears next to the galleries while the Vagrant instance is running.

**Comment by YukiSakuma** [comment]
There's no "Send to Archive" button for me here
![gallery](https://cloud.githubusercontent.com/assets/16185735/23491766/5c022a22-ff3b-11e6-99cb-8f302e9b1476.JPG)

**Comment by Sn0wCrack** [comment]
You have to enter onto a gallery or change your ExHentai to use the thumbnail view.

**Comment by YukiSakuma** [comment]
I tried thumbnail view of the galleries and going to the actual gallery but still missing
![thumb](https://cloud.githubusercontent.com/assets/16185735/23493564/b4c16428-ff47-11e6-9d65-fad56115fb3a.JPG)



![archive](https://cloud.githubusercontent.com/assets/16185735/23493361/2c336260-ff46-11e6-9126-26db39ddcabf.JPG)

**Comment by Sn0wCrack** [comment]
Seems like you haven't installed the userscript correctly then.
Did you change the key on the linux config, it needs to match on both the userscript and linux config.

**Comment by YukiSakuma** [comment]
I didn't change the key though so the key is changeme for both the linux config file and the userscript
```
	
"base": {
		"accessKey": "changeme",
        "autoReadPercentage": 80,
		"viewType": "mpv",
		"cookie": {
```

```
var baseUrl = 'https://localhost/';
var key = 'changeme';
```

**Comment by Sn0wCrack** [comment]
The only thing it can be if your vagrant instance is running is that the userscript didn't install correctly.
Double check your greasemonkey script list, perhaps try to install it manually if the drag and drop method isn't working.

**Comment by YukiSakuma** [comment]
It's already installed, I tried opening with firefox instead of drag and drop to install and it's still the same
![exhen](https://cloud.githubusercontent.com/assets/16185735/23501843/80b6c7e4-ff70-11e6-9bdc-1d2312965020.JPG)

**Comment by Sn0wCrack** [comment]
Oh, I think I've just noticed an error with the vagrant setup guide.
You might need to set the baseUrl as "https://localhost/vagrant/"

**Comment by YukiSakuma** [comment]
I've just changed the baseUrl of the userscript to "https://localhost/vagrant/" and reinstalled and restarted Vagrant but still "Send to Archive" is missing, I've already tried using it with Chrome and it's the same
Greasemonkey says the script is active though when I am on e-hentai or exhentai

**Comment by YukiSakuma** [comment]
While I'm no expert in userscript, I've already installed the userscript in different browsers and even browsers of a virtual guest OS and still can't see the actual "Send to archive" button while on e-h or ex even though grease or tapermonkey is saying the Exhentai archive script is active/enabled, so I think maybe the userscript code has a problem

**Comment by Sn0wCrack** [comment]
No there currently aren't any issues either the archive software or the userscript, I've tested this myself and I'm running the latest commit on my machine and it is currently fully functioning.

Open up the "inspect element" view in your browser and check the network tab when entering onto exhentai and then refresh the page, once the page has fully loaded post the results of that here.

**Comment by YukiSakuma** [comment]
![enabled](https://cloud.githubusercontent.com/assets/16185735/24291527/4b3f0508-10c4-11e7-9c7a-0a56e94f65f1.jpg)
E-hentai
![whenonehen](https://cloud.githubusercontent.com/assets/16185735/24291535/51c7c432-10c4-11e7-8681-78614ba82481.jpg)
Exhentai
![whenonexhen](https://cloud.githubusercontent.com/assets/16185735/24291540/57f273a2-10c4-11e7-9331-2987a7efaeb7.jpg)

**Comment by Sn0wCrack** [comment]
Put a slash at the end of your archiveUrl in the user script.

So it's like "/vagrant/"

**Comment by YukiSakuma** [comment]
I changed it to 
```
var baseUrl = 'https://localhost/vagrant/';
```
but still "The requested URL /vagrant/api.php was not found on this server."

![updateexehen](https://cloud.githubusercontent.com/assets/16185735/24317807/b0881e0a-1136-11e7-8da8-8c8182d2a107.jpg)
edit I found an api.php file inside the ExHentai-Archive-master\www folder and I moved it to ExHentai-Archive-master and now it's saying
"HTTP ERROR 500"

**Comment by Sn0wCrack** [comment]
try changing it back to "https://localhost/" including that last "/" there.

I've doubled check the vagrant stuff since it's been awhile, and that should be it.

**Comment by YukiSakuma** [comment]
Ok I changed it back to 
`var baseUrl = 'https://localhost/';`
but still it returns 500 internal server error, the api.php file I found was inside "ExHentai-Archive-master\www" folder and I just transferred it to the parent directory ExHentai-Archive-master\ so it can see it.

**Comment by Sn0wCrack** [comment]
The api files needs to be in the www folder.

Is your vagrant instance currently running as well?

**Comment by YukiSakuma** [comment]
Yes vagrant is vagrant up, I only copied the api.php so there is still api.php in the www folder, if there's no api.php in ExHentai-Archive-master parent directory, it will return 404 not found
edit: I removed the api.php from the parent directory while there is still api.php in the www folder but now it returns 500 internal error
When I am trying to access "https://localhost/api.php"
it will say "{"ret":false,"message":"Invalid request"}"

**Comment by Sn0wCrack** [comment]
Yeah I think this might be in relation to apache or the like getting an update and messing something up somewhere.

I'll take a look into this proper.

**Comment by Sn0wCrack** [comment]
Okay, seems the way PHP looks for files may have changed, please rename the "config.json.linux" to "config.json" and all should be fine. (keeping it in the root directory)

**Comment by YukiSakuma** [comment]
Finally that did the trick. I can finally see the send to archive button, I tried to send a gallery to archive then I ran https://localhost/vagrant/TaskRunner.php?task=Full but it outputs this
```
Running Task: Task_Full
DEBUG: [2017-03-25 02:50:29][ExArchiver] Archiving gallery: #1043723 DEBUG: [2017-03-25 02:50:32][ExArchiver] Downloading gallery archive ERROR: [2017-03-25 02:50:35][ExArchiver] Download check not submitted. DEBUG: [2017-03-25 02:50:35][ExArchiver] Archiving gallery: #1043942 DEBUG: [2017-03-25 02:50:37][ExArchiver] Downloading gallery archive ERROR: [2017-03-25 02:50:43][ExArchiver] Download check not submitted. DEBUG: [2017-03-25 02:50:43][ExArchiver] Archiving gallery: #1043895 DEBUG: [2017-03-25 02:50:45][ExArchiver] Downloading gallery archive ERROR: [2017-03-25 02:50:47][ExArchiver] Download check not submitted. DEBUG: [2017-03-25 02:50:47][ExArchiver] Archive complete. Archived 0 galleries. 
DEBUG: [2017-03-25 02:50:47][Task_Thumbnails] Processed thumbnails for 0 galleries 
Sphinx 2.2.11-id64-release (95ae9a6) Copyright (c) 2001-2016, Andrew Aksyonoff Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com) using config file '/etc/sphinxsearch/sphinx.conf'... indexing index 'galleries'... collected 3 docs, 0.0 MB sorted 0.0 Mhits, 100.0% done total 3 docs, 1439 bytes total 0.003 sec, 476647 bytes/sec, 993.70 docs/sec indexing index 'suggested'... collected 29 docs, 0.0 MB sorted 0.0 Mhits, 100.0% done total 29 docs, 316 bytes total 0.000 sec, 351111 bytes/sec, 32222.22 docs/sec total 44 reads, 0.000 sec, 0.1 kb/call avg, 0.0 msec/call avg total 24 writes, 0.000 sec, 0.4 kb/call avg, 0.0 msec/call avg rotating indices: successfully sent SIGHUP to searchd (pid=957). 
Array ( [0] => Sphinx 2.2.11-id64-release (95ae9a6) [1] => Copyright (c) 2001-2016, Andrew Aksyonoff [2] => Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com) [3] => [4] => using config file '/etc/sphinxsearch/sphinx.conf'... [5] => indexing index 'galleries'... [6] => collected 3 docs, 0.0 MB [7] => sorted 0.0 Mhits, 100.0% done [8] => total 3 docs, 1439 bytes [9] => total 0.002 sec, 487631 bytes/sec, 1016.60 docs/sec [10] => indexing index 'suggested'... [11] => collected 29 docs, 0.0 MB [12] => sorted 0.0 Mhits, 100.0% done [13] => total 29 docs, 316 bytes [14] => total 0.000 sec, 403061 bytes/sec, 36989.79 docs/sec [15] => total 44 reads, 0.000 sec, 0.1 kb/call avg, 0.0 msec/call avg [16] => total 24 writes, 0.000 sec, 0.4 kb/call avg, 0.0 msec/call avg [17] => rotating indices: successfully sent SIGHUP to searchd (pid=957). ) 
Finished Task Task_Full
Finished running task.
```
Am I missing something to do? It doesn't download.
I can see the unarchived galleries but there are no thumbnails and I need to move my mouse in that area in order for the gallery to show up
![unarc](https://cloud.githubusercontent.com/assets/16185735/24319036/abe5a1f0-114b-11e7-9b9d-0dffe92bc82c.jpg)

**Comment by YukiSakuma** [comment]
It's not really resolved because I was patiently waiting for your response to my comment above.

**Comment by Sn0wCrack** [comment]
I've closed it as it's not an issue with the code itself, it's more of a tech support thing.

And yes that's how it'll function if the gallery is unarchived currently, thumbnails are loaded from ExHentai directly so they take some time to display, and it's normal for the galleries to not appear unless you hover over them.

Make sure in the ExHentai settings (on the website itself) are set to the default option for the Archiver (Manual Select, Manual Start (Default)) and that you copy your cookie like that, or you can use the default one provided in the config file. Other than that I have no clue what the issue could be caused by, as the setup seemingly works fine for me, in vagrant and out.
