### ISSUE TITLE
Search bar not working

### ISSUE THREAD

**Issue by waifuchan** [Sn0wCrack/ExHentai-Archive#7]
Whenever I type a keyword it wont show a preview like it should and it infinitely loads when I hit enter.

I am on Ubuntu 16.04 and using apache2

**Comment by Sn0wCrack** [comment]
Have you made sure you've done both of these:
1. You've archived galleries correctly
2. You've re-indexed your Sphinx recently

I'm going to need a ton more info than this.

**Comment by waifuchan** [comment]
Turns out it was just my sphinx install that was the problem. I followed the tutorial on a fresh debian server instead of ubuntu and everything works flawless. thank you
