### ISSUE TITLE
mpv and spv don't work

### ISSUE THREAD

**Issue by ghost** [Sn0wCrack/ExHentai-Archive#9]
When switching the views with the button, the view changes to multipage view and then you cant switch back.

`            <div class="switches-outer">
                <label>
                    <span>SPV</span>
                    <input type="checkbox" name="viewertype" value="0" class="fancy-switch viewtype" />
                    <div>
                        <div></div>
                    </div>
                    <span>MPV</span>`

This is the portion of code im referring to

**Comment by ghost** [comment]
This is for chrome btw

**Comment by Sn0wCrack** [comment]
Yeah, this seems to be an issue within Chrome itself and how it handles jQuery's ".prop" function.
I've noticed however it works completely fine with the Unarchived option however, so I'm unsure as to why it does not work with the SPV and MPV switch, I'll take a look at it, but I'm not even entirely sure where to start with it myself.

**Comment by hayleyxyz** [comment]
https://github.com/Sn0wCrack/ExHentai-Archive/blob/master/www/js/exhen.js#L82

Could this be it? checked mispelled as chceked

**Comment by Sn0wCrack** [comment]
Whoops, sorry I didn't notice your comment early.
Yeah that seems to have fixed it now, weird that it seemed to work fine in Firefox however.
